repos:
  - repo: local
    hooks:
      - id: docformatter
        name: docformatter
        entry: docformatter -i
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        types: [python]
        language: system
        pass_filenames: true
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true