[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "server"
version = "1.0.0"

requires-python = ">=3.13"

[tool.pytest.ini_options]
pythonpath = "."

[tool.setuptools]
packages = ["src.server"]
